# ================================================================
# theme: dove
# ================================================================

title         : Dove
description   : A theme development project.
# title       : The title of your site
# description : Short description of your site's purpose.

author        : Techie Joe

version       : '0.0.5'
revision      : '2601.5'

baseurl       : '/dove'
base_url      : '/dove'
home_url      : '/dove'

lang          : 'en-US'
theme_color   : '#222'
color_scheme  : light dark

ghost         : bG9jYWxob3N0LHRlY2hpZS1qb2UuZ2l0aHViLmlvLGxvY2FsaG9zdDo0MDAw
# ghost: 'your-tracking-id'
# to track your ThemeJs.

# google_analytics: 'your-tracking-id'
# to track your website using Google Analytics.

# cloudflare_analytics: 'your-tracking-id'
# to track your website using Cloudflare Analytics.

# show_downloads: true/false
# to indicate whether to provide a download URL.

# github:
#   zip_url: http://example.com/download.zip
#   another_url: another_value

sass:
  style: compressed

defaults:
  - scope:
      path: ""
  - values:
      layout: default

plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  # - jekyll-paginate
  # - jekyll-redirect-from
  # - jekyll-sitemap
  # - jekyll-feed
  # - jemoji

# exclude these from Jekyll production (_site).
exclude:
  - ".editorconfig"
  - ".github"
  - ".gitignore"
  - ".sass-cache"
  - ".jekyll-cache"
  - ".jekyll-metadata"
  - "*.gem"
  - "*.gemspec"
  - Gemfile
  - Gemfile.lock
  - ".bundle"
  - vendor
  - script
  - node_modules
  - package-lock.json
  - package.json
  - gulpfile.js
  - CNAME
  - "*.x"
  - "*.ignore"
  - "*.backup"
  - "*.localhost"